export const EmployeeData =[
    {
        id:1,
        firstName:'krati',
        lastName:'Porwal',
        age:'21'
    },
    {
        id:2,
        firstName:'kratika',
        lastName:'jain',
        age:'25'
    },
    {
        id:3,
        firstName:'huzefa',
        lastName:'burhani',
        age:'22'
    }
]